import styles from './Privacy.module.sass'

const Privacy = () => (
    <div className='container'>
        <div className={styles.privacy}>
            <h1 className='h1'>Andyedge's privacy policy</h1>
            <p>Last updated on: September 1st, 2014</p>
            <p>Andyedge is committed to protecting your privacy.
                We will not sell or rent your information. andyedge is committed to respecting your privacy and protecting your
                personally-identifiable information (information that is capable of identifying you as an individual person),
                hereinafter referred to as “Personal Information.” By submitting Personal Information, you consent to andyedge’s use
                of such Personal Information as further described in this Privacy Notice. Please read this Privacy Notice to
                understand the ways in which we collect, use, and disclose information we receive from or about you through this site.
            </p>
            <p><h5 style={{ color: '#4d4d4d' }}><strong>Collection of Personal Information.</strong></h5><br />
                You may access and browse our site without disclosing any Personal Information.  We will collect Personal Information
                from or about you in the following instances:</p> <p><h5 style={{ textDecoration: 'underline' }}>Information you provide.
                </h5>  We will collect and store any Personal Information you enter on our site or provide to us in some other manner.
                For example:</p> <p>If you register for or apply for jobs through the andyedge website, register for any andyedge or
                    affiliate newsletters and alerts, and participate in user-posting areas (such as bulletin boards, discussion forums, and surveys). </p> <p>If you request information, products, or services from andyedge, or ask us to resolve questions or concerns, we will ask you to provide information such as your name, contact information, and other identifying information necessary to respond to a particular inquiry. </p> <p>If you respond to surveys, assessment tools, questionnaires, and other forms of feedback requests, we will collect information from you that you provide in such settings. </p> <p> <h5 style={{ color: '#4d4d4d' }}><strong>Use of Cookies and Other Technologies To Collect Information On Our Web Site.</strong></h5><br />
                Our site will automatically collect information from or about your computer when you visit, such as your browser type, the website you came from (known as the referring URL), the time and date of your access, and your Internet Protocol address.
            </p> <p>We also collect information through cookies and other technologies to help us keep track of your interactions with our site. If you have shared Personal Information, such as an e-mail address or username, we will include a portion of this information in a cookie so that we can recognize you and remember your selections when you return to our site. Please note that your web browser can be set to allow you to control whether you will accept cookies, reject cookies, or to notify you each time a cookie is sent.</p> <p>We also use standard Internet technology, such as Internet tags (also known as Web beacons, action tags, or GIFs) in combination with cookies at our site and will deploy these tags through an advertising company. These tags are placed on both online advertisements that bring users to our site and on different pages within our site. We use this technology to measure visitors' responses to our site and the effectiveness of our advertising campaigns (including how many times a page is opened and which information is consulted). Please be assured that we do not collect or seek through these tags or cookies any Personal Information about our visitors.</p> <p>Cookies or Internet tags may also be used within certain promotional e-mail communications or in conjunction with such communications sent by us or our business partners for the purpose of tracking whether a promotion was viewed by the e-mail recipient or someone the e-mail was referred to. These cookies or Internet tags are not linked to your Personal Information.</p> <p>The laws in many European Union countries require you to provide a form of consent before cookies are placed on your web browser unless the cookie is necessary for the website to work. </p> <p>There is no agreed standard for how companies comply with these laws. We do the following: We only use cookies where they are necessary for our services or where you have provided your express or implied consent. We respect your wishes, and you can inspect, delete, or block any cookies used by us by selecting the appropriate control in your web browser. We support technologies that have been developed and are being developed for your web browser that allows you to be more selective about the cookies that your web browser will accept.</p>
            <p><h5 style={{ color: '#4d4d4d' }}><strong>Disclosures of Information. </strong></h5><br />
                We will not sell or rent any Personal Information (including e-mail address) we collect.  </p> <p>We will share your information with andyedge affiliates in order to deliver the services, products and information offered by andyedge.   andyedge will not intentionally disclose or transfer (and shall take reasonable steps to prevent the unauthorized or accidental disclosure of) your Personal Information to third parties (i.e., persons or entities that are not affiliates of andyedge) without your consent, whether for such third parties’ marketing purposes or otherwise, except as follows. andyedge may provide access to your Personal Information to third party vendors engaged by andyedge to provide services related to the site; provided that such vendors will first agree to maintain the confidentiality of such information and provide the same level of data security as provided by andyedge. andyedge may also be compelled to surrender Personal Information to legal authorities without express user consent if presented with a court subpoena or similar legal order, or as required or permitted by the laws, rules, and regulations of any applicable jurisdiction. Also, in the event of a violation of the Terms of Use of or any other terms on this site, including but not limited to a violation of any restrictions on use of materials provided in or through this site, andyedge may disclose Personal Information to affected parties and legal authorities in furtherance of potential or on-going legal proceedings. </p> <p><h5><strong>User forums</strong></h5><br />
                andyedge reserves the right to remove and/or block any content from its forums or any page on its site.  andyedge is not responsible for the views or opinions expressed by any users on the forum and/or other pages of the site.  You should be aware that whenever you publicly-disclose information online, that information could be collected and used by others. andyedge is not responsible for any action or policies of any third parties who collect information that users publicly disclose in any such forums on the site.  andyedge may use any information (including images) posted on any page of our site; by posting any such information on andyedge’s site, you consent to andyedge’s future use.  </p> <p><h5><strong>Newsletters and Alerts</strong></h5><br />
                By registering for recurring andyedge newsletters or alerts, you agree to receive on occasion other correspondence from andyedge related to the subscribed newsletters and other andyedge news and information that you consented to receive during registration. This type of information is shared externally only in anonymous, aggregated form for generalized user analysis or to enable third party agents to send e-mails to you on our behalf. You will be contacted by e-mail or otherwise only by andyedge or it agents. </p> <p>We ask for your e-mail address at registration. We will send e-mails to this address to confirm your registration, to provide newsletters or alerts and to contact you for any other reason. In addition, we may contact you regarding your account status. If you sign up to receive any of our newsletters, alerts, or surveys, you may on occasion receive other correspondence from andyedge. Your e-mail address will not be shared with any third party other than an agent who has agreed to send e-mails on our behalf. </p> <p>The site also includes a feature that enables andyedge to send links to its content through e-mail at our users' request. The e-mail address(es) that you supply in connection with this service will be used only to send the requested content. They will not be stored or reused for any purpose. </p> <p><h5 style={{ color: '#4d4d4d' }}><strong>Your Choices.</strong></h5><br />
                You have a choice about the receipt of e-mails.  Once subscribed, you can subsequently opt out through any of the emails we send. </p> <p><h5 style={{ color: '#4d4d4d' }}><strong>Accessing and Updating Your Information. </strong></h5><br />
                You can also update your information, or instruct us to remove you from the email list by sending a message via: <a href="http://www.andyedge.com/contact.html">contact</a>.</p> <p><h5 style={{ color: '#4d4d4d' }}><strong>Security and Compliance.</strong></h5><br />
                We maintain reasonable and appropriate technical, administrative and physical safeguards to protect Personal Information from loss, misuse, or alteration.  For example, we use industry-standard encryption technologies when we collect or transmit sensitive Personal Information. We also comply with all laws that require us to protect your Personal Information. Despite these precautions, andyedge, however, cannot guarantee that unauthorized persons will not obtain access to your Personal Information. </p> <p>We do not knowingly collect Personal Information directly from any person under the age of 13. </p> <p><h5 style={{ color: '#4d4d4d' }}><strong>Date Retention Policy</strong></h5><br />
                andyedge stores Personal Information for various purposes as notified to you in Privacy Notice. For each of these different purposes, andyedge only retains the Personal Information for so long as it is serving its notified purpose.</p> <p><h5 style={{ color: '#4d4d4d' }}><strong>Privacy Practices of Other Sites and Entities. </strong></h5><br />
                Please note that this site contains information about and links to other sites that are not owned or controlled by andyedge.  If you click on a link provided on our site, you will be directed to a website that operates under a different privacy policy.  We are not responsible for the privacy practices of other sites or entities, and we recommend that you examine the privacy statements of these other sites and entities to understand their procedures for collecting, using, and disclosing personal information.</p> <p><h5 style={{ color: '#4d4d4d' }}><strong>Changes to this Privacy Notice.</strong></h5><br />
                We reserve the right to modify this Privacy Notice at any time, so please review it frequently.  You can determine whether the Privacy Notice has changed by reviewing the date posted at the top.  If we make any material changes to this Privacy Notice, we will post notice of the change on our site or notify you in other ways we deem appropriate to keep you informed of our information practices. </p> <p><h5 style={{ color: '#4d4d4d' }}><strong>Contact Us.</strong></h5><br />
                If you have questions or concerns regarding this Privacy Notice, you should send a message via: <a href="http://www.andyedge.com/contact.html">contact</a>. </p>
        </div>
    </div>
)

export default Privacy