export * from './entities/whatPage.adapter'
export * from './entities/whyPage.adapter'
export * from './entities/ecampPage.adapter'
export * from './entities/header.adapter'
export * from './entities/bomou.adapter'