export * from './entities/header.adapter'
export * from './entities/whatPage.adapter'
export * from './entities/whyPage.adapter'
export * from './entities/ecampPage.adapter'
export * from './entities/bomou.adapter'
export * from './entities/pearson.adapter'
export * from './entities/mediumCaseStudy.adapter'
export * from './entities/smallCaseStudy.adapter'